
pub fn words() -> [[&'static str; 2]; 150] {






    let _words = [
    ["mesa", "Superfície plana e geralmente retangular, apoiada por pernas, usada para colocar objetos ou realizar refeições."],
    ["cadeira", "Assento comum com encosto, utilizado por uma pessoa para descansar ou se sentar confortavelmente."],
    ["luminaria", "Dispositivo elétrico ou a gás para iluminar ambientes, com diversas formas e tamanhos."],
    ["martelo", "o martelo é uma ferramenta usada para bater ou fixar objetos, geralmente associada a trabalhos de construção ou reparo. além de sua função prática de trabalho manual, os martelos também têm significados simbólicos, representando força, poder e habilidade. eles podem ser vistos como símbolos de determinação e capacidade de construir ou consertar coisas."],
    ["espelho", "Superfície refletora, geralmente feita de vidro, metal ou plástico, que reflete a imagem de quem se aproxima."],
    ["geladeira", "Eletrodoméstico usado para refrigerar e conservar alimentos, geralmente com compartimentos para diferentes tipos de comida."],
    ["teclado", "Conjunto de teclas usado para inserir dados em um dispositivo eletrônico, como um computador ou smartphone."],
    ["bicicleta", "Veículo de duas rodas movido por pedaladas, usado para transporte ou exercício físico."],
    ["carteira", "Pequeno acessório usado para guardar dinheiro, cartões e documentos, geralmente feito de couro ou material sintético."],
    ["telefone", "Dispositivo de comunicação eletrônica usado para fazer chamadas de voz ou vídeo, enviar mensagens e acessar a internet."],
    ["escova", "Utensílio com cerdas usado para limpar ou pentear cabelos, roupas, dentes ou superfícies diversas."],
    ["caneta", "Instrumento de escrita que contém tinta e é usado para escrever ou desenhar em papel ou outras superfícies."],
    ["janela", "Abertura em uma parede ou superfície que permite a entrada de luz e ar em um ambiente, geralmente coberta por vidro."],
    ["relogio", "Dispositivo usado para medir e exibir o tempo, geralmente composto por um mostrador e ponteiros ou números digitais."],
    ["notebook", "Computador portátil com tela, teclado e touchpad integrados, usado para trabalho, estudo ou entretenimento."],
    ["copo", "Recipiente com uma abertura na parte superior, usado para beber líquidos como água, suco, café ou chá."],
    ["lapis", "Instrumento de escrita feito de madeira com uma mina de grafite no centro, usado para escrever ou desenhar."],
    ["chave", "Objeto metálico usado para abrir ou fechar fechaduras de portas, cadeados, armários e outros dispositivos similares."],
    ["abajur", "Luminária de mesa, geralmente com uma base e uma cúpula, usada para iluminar um ambiente de forma suave."],
    ["leopardo", "Felino de grande porte encontrado em várias regiões da África e da Ásia, conhecido por suas manchas e habilidades de caça."],
    ["golfinho", "Mamífero marinho conhecido por sua inteligência e habilidade de nadar e pular fora da água."],
    ["elefante", "Mamífero terrestre de grande porte, conhecido por sua tromba longa e presas curvadas."],
    ["papagaio", "Ave com cores vibrantes, conhecida por sua capacidade de imitar sons e falar algumas palavras."],
    ["baleia", "Mamífero marinho de grande porte, conhecido por sua tamanho imponente e suas canções complexas."],
    ["tigre", "Grande felino encontrado principalmente na Ásia, conhecido por suas listras e habilidades de caça."],
    ["panda", "Mamífero herbívoro da Ásia, conhecido por sua pelagem preta e branca e por se alimentar de bambu."],
    ["cavalo", "Mamífero domesticado utilizado para transporte, trabalho e atividades recreativas, conhecido por sua força e velocidade."],
    ["leao", "Felino de grande porte encontrado na África, conhecido por sua juba e por ser o rei da selva."],
    ["gato", "Felino domesticado, conhecido por sua agilidade, flexibilidade e independência."],
    ["jacare", "Réptil semiaquático com corpo alongado e mandíbulas fortes, encontrado em pântanos e rios."],
    ["aguia", "Ave de rapina com excelente visão e garras afiadas, conhecida por sua força e agilidade em voo."],
    ["cachorro", "Animal de estimação conhecido por sua lealdade e diversidade de raças."],
    ["girafa", "Mamífero com pescoço longo, encontrado na África, conhecido por ser o animal terrestre mais alto do mundo."],
    ["elefante", "Mamífero terrestre de grande porte, conhecido por sua tromba longa e presas curvadas."],
    ["coala", "Mamífero marsupial da Austrália, conhecido por sua aparência fofa e por se alimentar principalmente de eucalipto."],
    ["hipopotamo", "Mamífero herbívoro semiaquático, conhecido por seu tamanho robusto e agressividade quando ameaçado."],
    ["leopardo", "Felino de grande porte encontrado em várias regiões da África e da Ásia, conhecido por suas manchas e habilidades de caça."],
    ["pinguim", "Ave marinha não voadora, conhecida por suas habilidades de natação e por viver em regiões polares e temperadas."],
    ["medico", "Profissional de saúde treinado para diagnosticar, tratar e prevenir doenças e lesões em pacientes."],
    ["advogado", "Profissional especializado em direito, responsável por fornecer aconselhamento jurídico e representação legal."],
    ["engenheiro", "Profissional especializado em aplicar princípios científicos e matemáticos para projetar e construir estruturas e sistemas."],
    ["professor", "Educador que fornece instrução e orientação acadêmica para alunos em várias disciplinas e níveis."],
    ["dentista", "Profissional de saúde especializado em cuidados dentários, incluindo prevenção, diagnóstico e tratamento de problemas dentários."],
    ["enfermeiro", "Profissional de saúde responsável por cuidar e tratar pacientes sob a supervisão de médicos."],
    ["psicologo", "Profissional especializado no estudo da mente humana e do comportamento, e na prestação de aconselhamento e terapia psicológica."],
    ["arquiteto", "Profissional responsável pelo planejamento e design de edifícios e espaços urbanos."],
    ["jornalista", "Profissional que coleta, escreve e relata notícias e informações para o público através de vários meios de comunicação."],
    ["piloto", "Profissional treinado para operar aeronaves e garantir a segurança dos passageiros durante o voo."],
    ["contador", "Profissional responsável por manter registros financeiros precisos e preparar relatórios fiscais para indivíduos e empresas."],
    ["veterinario", "Profissional de saúde animal treinado para diagnosticar, tratar e prevenir doenças em animais."],
    ["biologo", "Profissional que estuda organismos vivos e suas interações com o meio ambiente."],
    ["fotografo", "Profissional que utiliza câmeras para capturar imagens de eventos, pessoas, paisagens e objetos."],
    ["programador", "Profissional de tecnologia da informação que escreve, testa e mantém código de computador para desenvolver software e aplicativos."],
    ["chef", "Profissional treinado em preparar e apresentar alimentos em restaurantes, hotéis e outras instalações de serviços de alimentação."],
    ["designer", "Profissional responsável por criar soluções visuais para comunicações gráficas, produtos e ambientes."],
    ["pescador", "Profissional que trabalha na captura de peixes e outros organismos aquáticos para alimentação ou comércio."],
    ["bombeiro", "Profissional treinado para combater incêndios, realizar operações de resgate e prestar primeiros socorros em emergências."],
    ["psiquiatra", "Médico especializado em diagnosticar, tratar e prevenir transtornos mentais e emocionais."],
    ["correr", "Mover-se rapidamente usando as pernas."],
    ["saltar", "Elevar-se no ar usando os músculos das pernas."],
    ["dancar", "Mover-se ritmicamente ao som da música."],
    ["cantar", "Produzir sons musicais com a voz."],
    ["cozinhar", "Preparar alimentos utilizando calor."],
    ["escrever", "Expressar pensamentos ou ideias em forma escrita."],
    ["ler", "Examinar e compreender o significado de textos escritos."],
    ["estudar", "Aplicar a mente para adquirir conhecimento."],
    ["trabalhar", "Realizar atividades produtivas em troca de remuneração."],
    ["viajar", "Mover-se de um lugar para outro."],
    ["aprender", "Adquirir conhecimento ou habilidades."],
    ["construir", "Criar ou montar algo usando materiais."],
    ["observar", "Examinar ou assistir atentamente algo."],
    ["sorrir", "Expressar felicidade com o rosto."],
    ["abrir", "Mover ou separar algo para permitir o acesso."],
    ["fechar", "Mover ou unir algo para bloquear o acesso."],
    ["comer", "Ingerir alimentos para sustento ou prazer."],
    ["dormir", "Entrar em um estado de repouso profundo."],
    ["ouvir", "Perceber sons por meio do sentido auditivo."],
    ["brincar", "Participar de atividades lúdicas ou recreativas."],
    ["restaurante", "Estabelecimento onde as pessoas podem comprar e comer refeições preparadas."],
    ["parque", "Área pública ou privada com gramados, árvores e espaços de lazer para atividades ao ar livre."],
    ["escola", "Instituição educacional onde os alunos recebem instrução e realizam atividades acadêmicas."],
    ["praia", "Região costeira de areia e água, frequentemente visitada por banhistas e turistas."],
    ["museu", "Instituição dedicada à preservação, exibição e estudo de artefatos culturais, históricos e científicos."],
    ["hospital", "Instituição de saúde onde os pacientes recebem tratamento médico e cuidados de enfermagem."],
    ["cinema", "Local onde as pessoas assistem a filmes em uma tela grande, geralmente com som surround."],
    ["teatro", "Local destinado à apresentação de peças teatrais, musicais, danças e outras formas de entretenimento ao vivo."],
    ["biblioteca", "Local onde as pessoas podem emprestar livros, estudar e acessar recursos de informação."],
    ["mercado", "Estabelecimento comercial onde os clientes podem comprar uma variedade de produtos alimentícios e de consumo."],
    ["parque", "Área pública ou privada com gramados, árvores e espaços de lazer para atividades ao ar livre."],
    ["estação", "Local onde trens, ônibus, metrôs ou outros meios de transporte fazem paradas regulares para embarque e desembarque de passageiros."],
    ["shopping", "Centro comercial com diversas lojas, restaurantes e serviços, frequentemente visitado para compras e entretenimento."],
    ["igreja", "Edifício usado para serviços religiosos e práticas de culto em várias religiões."],
    ["estadio", "Local onde ocorrem eventos esportivos, como jogos de futebol, rugby, cricket, entre outros."],
    ["piscina", "Estrutura artificial destinada ao banho, natação e lazer aquático."],
    ["escola", "Instituição educacional onde os alunos recebem instrução e realizam atividades acadêmicas."],
    ["parque", "Área pública ou privada com gramados, árvores e espaços de lazer para atividades ao ar livre."],
    ["aeroporto", "Local onde aeronaves decolam e pousam, e onde passageiros embarcam e desembarcam de voos."],
    ["praca", "Área pública com bancos, jardins e fontes, frequentemente usada como ponto de encontro e lazer."],
    ["infimo", "Que tem valor muito baixo ou insignificante."],
    ["interim", "Período de tempo entre dois eventos ou estados."],
    ["perene", "Que dura por um longo período de tempo ou é duradouro."],
    ["subito", "Que acontece de repente ou sem aviso prévio."],
    ["aureo", "Que tem a cor ou o brilho do ouro; dourado."],
    ["ecletico", "Que se refere a algo que é composto por elementos de diferentes estilos ou origens."],
    ["fulgido", "Que brilha intensamente; resplandecente."],
    ["longinquo", "Que está muito distante no tempo ou no espaço."],
    ["modico", "Que tem um valor modesto ou insignificante."],
    ["pifio", "Que é insignificante, irrelevante ou sem importância."],
    ["quimera", "Ideia ou projeto ilusório e irrealizável."],
    ["vivido", "Que é muito brilhante, intenso ou vívido."],
    ["zenite", "Ponto mais alto ou culminante de algo; auge."],
    ["osculo", "Beijo, especialmente um beijo afetuoso ou amoroso."],
    ["exilio", "A condição de ser forçado a viver longe de seu país de origem."],
    ["eximio", "Que é muito habilidoso ou talentoso em alguma atividade."],
    ["amago", "Parte central ou essencial de algo; o cerne."],
    ["animo", "Coragem, determinação ou espírito."],
    ["obice", "Obstáculo, impedimento ou objeção."],
    ["postumo", "Que ocorre após a morte de alguém, especialmente referente a obras publicadas após a morte do autor."],
    ["adjacente", "Que está próximo ou ao lado de algo; vizinho."],
    ["aspero", "Que tem uma superfície áspera ou irregular; rugoso."],
    ["computo", "Ação de calcular ou contar; computação."],
    ["cuspide", "Ponto mais alto ou pontiagudo de algo; o auge."],
    ["discreto", "Que é reservado, cauteloso ou modesto em comportamento."],
    ["efficaz", "Que é eficiente ou produz o efeito desejado."],
    ["espolio", "Bens e propriedades deixados por uma pessoa falecida; herança."],
    ["exortar", "Incitar, encorajar ou aconselhar veementemente alguém a fazer algo."],
    ["impeto", "Força ou impulso que impulsiona algo em movimento; ímpeto."],
    ["integro", "Que é honesto, justo e incorruptível em caráter."],
    ["nausea", "Sensação de desconforto no estômago, geralmente associada a vontade de vomitar."],
    ["obulo", "Pequena quantia de dinheiro ou contribuição; esmola."],
    ["odio", "Sentimento intenso de aversão, repulsa ou hostilidade em relação a alguém ou algo."],
    ["afeto", "Expressão de sentimentos ou emoções de forma carinhosa ou afetuosa."],
    ["regio", "Que é magnífico, grandioso ou digno de um rei."],
    ["relevante", "Que é significativo, importante ou pertinente em uma determinada situação."],
    ["sequito", "Grupo de seguidores ou assistentes que acompanham uma pessoa importante."],
    ["torrido", "Que é extremamente quente ou fervente."],
    ["vultoso", "Que é grande em quantidade ou valor; considerável."],
    ["vitreo", "Que é feito de vidro ou tem a aparência de vidro; vidroso."],
    ["asma", "Doença respiratória crônica caracterizada por dificuldade em respirar devido ao estreitamento das vias aéreas."],
    ["cancer", "Doença caracterizada pelo crescimento descontrolado de células anormais que podem invadir e destruir tecidos saudáveis."],
    ["diabetes", "Doença metabólica caracterizada por níveis elevados de glicose no sangue devido à produção insuficiente de insulina ou à resistência à insulina."],
    ["hepatite", "Inflamação do fígado, muitas vezes causada por vírus, álcool, toxinas ou doenças autoimunes."],
    ["hipertensao", "Condição crônica caracterizada por pressão arterial elevada nas artérias, o que aumenta o risco de doenças cardiovasculares."],
    ["obesidade", "Condição caracterizada pelo acúmulo excessivo de gordura corporal, aumentando o risco de doenças crônicas como diabetes e doenças cardiovasculares."],
    ["artrite", "Inflamação das articulações, resultando em dor, rigidez e dificuldade de movimento."],
    ["alergia", "Resposta exagerada do sistema imunológico a substâncias inofensivas, causando sintomas como espirros, coceira e erupções cutâneas."],
    ["anemia", "Condição caracterizada pela redução dos glóbulos vermelhos ou pela diminuição da hemoglobina no sangue, resultando em fadiga e fraqueza."],
    ["cistite", "Inflamação da bexiga, geralmente causada por infecção bacteriana e caracterizada por dor ao urinar e frequência urinária aumentada."],
    ["epilepsia", "Distúrbio neurológico caracterizado por convulsões recorrentes, que podem variar em intensidade e frequência."],
    ["catapora", "Infecção viral altamente contagiosa caracterizada por erupções cutâneas pruriginosas e febre."],
    ];
    _words

} 

// The array contains the ascii representation of each letter in the alfabet, with a stardard height of 8 lines and a variable lenght, the usize passed in the tuple
pub fn char_to_ascii(character: char) ->  ([&'static str; 8], i32) {

    let ascii: ([&'static str; 8], i32);

    let ascii_drawnings: [([&'static str; 8], i32); 28] = [
         
        ([
        r#" "#,
        r#" "#,
        r#"  __ _ "#,
        r#" / _` |"#,
        r#"| (_| |"#,
        r#" \__,_|"#,
        r#" "#,
        r#" "#], 7),

        ([
        r#" _ "#,
        r#"| |"#,
        r#"| |__"#,
        r#"| '_ \ "#,
        r#"| |_) |"#,
        r#"|_.__/ "#,
        r#" "#,
        r#" "#], 7),

        ([
        r#" "#,
        r#" "#,
        r#"  ___ "#,
        r#" / __|"#,
        r#"| (__ "#,
        r#" \___|"#,
        r#" "#,
        r#" "#], 6),

        ([
        r#"     _ "#,
        r#"    | |"#,
        r#"  __| |"#,
        r#" / _` |"#,
        r#"| (_| |"#,
        r#" \__,_|"#,
        r#" "#,
        r#" "#], 7),

        ([
        r#" "#,
        r#" "#,
        r#"  ___ "#,
        r#" / _ \"#,
        r#"|  __/"#,
        r#" \___|"#,
        r#" "#,
        r#" "#], 6),

        ([
        r#"  __"#,
        r#" / _| "#,
        r#"| |_ "#,
        r#"|  _| "#,
        r#"| |  "#,
        r#"|_|  "#,
        r#" "#,
        r#" "#], 5),

        ([
        r#" "#,
        r#" "#,
        r#"  __ _ "#,
        r#" / _` |"#,
        r#"| (_| |"#,
        r#" \__, |"#,
        r#"  __/ |"#,
        r#" |___/ "#], 7),

        ([
        r#" _"#,
        r#"| |"#,
        r#"| |_"#,
        r#"| '_ \"#,
        r#"| | | |"#,
        r#"|_| |_|"#,
        r#" "#,
        r#" "#], 7),

        ([
        r#" _"#,
        r#"(_)"#,
        r#" _ "#,
        r#"| |"#,
        r#"| |"#,
        r#"|_|"#,
        r#" "#,
        r#" "#], 3),

        ([
        r#"   _ "#,
        r#"  (_)"#,
        r#"   _ "#,
        r#"  | |"#,
        r#"  | |"#,
        r#"  | |"#,
        r#" _/ |"#,
        r#"|__/ "#], 5),

        ([
        r#" _"#,
        r#"| |"#,
        r#"| | __"#,
        r#"| |/ / "#,
        r#"|   < "#,
        r#"|_|\_\"#,
        r#" "#,
        r#" "#], 6),

        ([
        r#" _"#,
        r#"| |"#,
        r#"| |"#,
        r#"| |"#,
        r#"| |"#,
        r#"|_|"#,
        r#" "#,
        r#" "#], 3),

        ([
        r#" "#,
        r#" "#,
        r#" _ __ _ __ "#,
        r#"| '_ ` _  \"#,
        r#"| | | | | |"#,
        r#"|_| |_| |_|"#,
        r#" "#,
        r#" "#], 11),

        ([
        r#" "#,
        r#" "#,
        r#" _ __ "#,
        r#"| '_ \ "#,
        r#"| | | |"#,
        r#"|_| |_|"#,
        r#" "#,
        r#" "#], 7),

        
        ([
        r#" "#,
        r#" "#,
        r#"  ___ "#,
        r#" / _ \ "#,
        r#"| (_) |"#,
        r#" \___/"#,
        r#" "#,
        r#" "#], 7),

        ([
        r#" "#,
        r#" "#,
        r#" _ __ "#,
        r#"| '_ \ "#,
        r#"| |_) |"#,
        r#"| .__/ "#,
        r#"| |"#,
        r#"|_|"#], 7),

        ([
        r#" "#,
        r#" "#,
        r#"  __ _ "#,
        r#" / _` |"#,
        r#"| (_| |"#,
        r#" \__, |"#,
        r#"    | |"#,
        r#"    |_|"#], 7),

        ([
        r#" "#,
        r#" "#,
        r#" _ __ "#,
        r#"| '__|"#,
        r#"| |"#,
        r#"|_|"#,
        r#" "#,
        r#" "#], 6),

        ([
        r#" "#,
        r#" "#,
        r#" ___"#,
        r#"/ __|"#,
        r#"\__ \ "#,
        r#"|___/"#,
        r#" "#,
        r#" "#], 5),

        ([
        r#" _"#,
        r#"| |"#,
        r#"| |"#,
        r#"| __|"#,
        r#"| |_"#,
        r#" \__|"#,
        r#" "#,
        r#" "#], 5),

        ([
        r#" "#,
        r#" "#,
        r#" _   _ "#,
        r#"| | | |"#,
        r#"| |_| |"#,
        r#" \__,_|"#,
        r#" "#,
        r#" "#], 7),

        ([
        r#" "#,
        r#" "#,
        r#"__   __"#,
        r#"\ \ / /"#,
        r#" \ V /"#,
        r#"  \_/ "#,
        r#" "#,
        r#" "#], 7),

        ([
        r#" "#,
        r#" "#,
        r#"__      __"#,
        r#"\ \ /\ / /"#,
        r#" \ V  V / "#,
        r#"  \_/\_/  "#,
        r#" "#,
        r#" "#], 11),

        ([
        r#" "#,
        r#" "#,
        r#"__  __"#,
        r#"\ \/ /"#,
        r#" >  <"#,
        r#"/_/\_\"#,
        r#" "#,
        r#" "#], 7),

        ([
        r#" "#,
        r#" "#,
        r#" _   _ "#,
        r#"| | | |"#,
        r#"| |_| |"#,
        r#" \__, |"#,
        r#"  __/ |"#,
        r#" |___/ "#], 7),
        
        ([
        r#" "#,
        r#" "#,
        r#" ____"#,
        r#"|_  /"#,
        r#" / /"#,
        r#"/___|"#,
        r#" "#,
        r#" "#], 5),


        // This is the ascii of a space, nothing important, it just pass some usize value to be used as a space
        ([ 
            r#" "#,
            r#" "#,
            r#" "#,
            r#" "#,
            r#" "#,
            r#" "#,
            r#" "#,
            r#" "#], 7),

        // This is the ascii for an _, this is important!
        ([ 
            r#" "#,
            r#" "#,
            r#" "#,
            r#" "#,
            r#" "#,
            r#" __________"#,
            r#" "#,
            r#" "#], 11),
        
    ];

    match character {
        'a' => ascii = ascii_drawnings[0],
        'b' => ascii = ascii_drawnings[1],
        'c' => ascii = ascii_drawnings[2],
        'd' => ascii = ascii_drawnings[3],
        'e' => ascii = ascii_drawnings[4],
        'f' => ascii = ascii_drawnings[5],
        'g' => ascii = ascii_drawnings[6],
        'h' => ascii = ascii_drawnings[7],
        'i' => ascii = ascii_drawnings[8],
        'j' => ascii = ascii_drawnings[9],
        'k' => ascii = ascii_drawnings[10],
        'l' => ascii = ascii_drawnings[11],
        'm' => ascii = ascii_drawnings[12],
        'n' => ascii = ascii_drawnings[13],
        'o' => ascii = ascii_drawnings[14],
        'p' => ascii = ascii_drawnings[15],
        'q' => ascii = ascii_drawnings[16],
        'r' => ascii = ascii_drawnings[17],
        's' => ascii = ascii_drawnings[18],
        't' => ascii = ascii_drawnings[19],
        'u' => ascii = ascii_drawnings[20],
        'v' => ascii = ascii_drawnings[21],
        'w' => ascii = ascii_drawnings[22],
        'x' => ascii = ascii_drawnings[23],
        'y' => ascii = ascii_drawnings[24],
        'z' => ascii = ascii_drawnings[25],
        ' ' => ascii = ascii_drawnings[26],
        '_' => ascii = ascii_drawnings[27],
        _ => panic!("erro ao transformar char em ascii"),
    }

    ascii
}
